source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'Demo' do
  pod 'TimeAgoInWords', path: "../TimeAgoInWords.podspec"
end

target 'DemoTests' do
  pod 'TimeAgoInWords', path: "../TimeAgoInWords.podspec"
end
